# Generated by Django 5.1.6 on 2025-03-09 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobapplication_worker'),
        ('users', '0003_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='customuser_applications', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='connected_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jobs_posted',
            field=models.ManyToManyField(blank=True, related_name='customuser_jobs_posted', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='customuser_skills', to='users.skill'),
        ),
    ]
