# Generated by Django 5.1.6 on 2026-01-16 04:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_add_interview_workflow'),
        ('users', '0008_customuser_address_en_customuser_address_tl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Location for job notifications (can be different from profile location)', null=True, srid=4326)),
                ('notification_radius_km', models.DecimalField(decimal_places=2, default=1.0, help_text='Radius in kilometers to search for jobs (e.g., 1.0, 5.0, 10.0)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable job notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, help_text='General job categories user wants to receive notifications for', related_name='subscribed_users', to='jobs.generalcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
