 # Generated by Django 5.1.6 on 2025-02-18 08:09                                                                    
                                                                                                                    
import django.db.models.deletion                                                                                    
from django.db import migrations, models                                                                            
                                                                                                                    
                                                                                                                    
class Migration(migrations.Migration):                                                                              
                                                                                                                    
    initial = True                                                                                                  
                                                                                                                    
    dependencies = [                                                                                                
        ('jobs', '0001_initial'),                                                                                   
        ('users', '0001_initial'),                                                                                  
    ]                                                                                                               
                                                                                                                    
    operations = [                                                                                                  
        migrations.AddField(                                                                                        
            model_name='jobposting',                                                                                
            name='client',                                                                                          
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),            
        ),                                                                                                          
    ] 
