# Generated by Django 5.1.6 on 2025-02-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcategory_remove_jobposting_client_job'),
        ('messaging', '0003_alter_message_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
