# Generated by Django 5.1.6 on 2025-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_picture',
            field=models.ImageField(blank=True, null=True, upload_to='job_pics/'),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
