# Generated by Django 5.1.6 on 2025-12-07 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobapplication_options_contract_agreed_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Daily end time (e.g., 5:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Daily start time (e.g., 9:00 AM)', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Daily end time (e.g., 5:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Daily start time (e.g., 9:00 AM)', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash')], default='Cash', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Available start time')),
                ('end_time', models.TimeField(help_text='Available end time')),
                ('is_available', models.BooleanField(default=True, help_text='Toggle availability for this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Worker Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('worker', 'day_of_week', 'start_time')},
            },
        ),
    ]
