# Generated by Django 5.1.6 on 2026-01-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_contract_end_time_contract_start_time_and_more'),
        ('jobs', '0017_re_add_translation_fields_to_historical_models'),
    ]

    operations = [
    ]
