# Generated by Django 5.1.6 on 2026-01-04 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_merge_20260104_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'General Category',
                'verbose_name_plural': 'General Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='job_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_description_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_title_tl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes_en',
            field=models.TextField(blank=True, help_text='Special terms or notes', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes_tl',
            field=models.TextField(blank=True, help_text='Special terms or notes', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason_en',
            field=models.TextField(blank=True, default='', help_text='Reason for termination request', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason_tl',
            field=models.TextField(blank=True, default='', help_text='Reason for termination request', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_en',
            field=models.TextField(blank=True, help_text='Contract terms and conditions', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='terms_tl',
            field=models.TextField(blank=True, help_text='Contract terms and conditions', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_tl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks_en',
            field=models.TextField(default='job to be done', help_text='List specific tasks expected from the worker.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks_tl',
            field=models.TextField(default='job to be done', help_text='List specific tasks expected from the worker.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_tl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_notes_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='certifications_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='certifications_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_tl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message_en',
            field=models.TextField(blank=True, help_text='Optional message to employer', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message_tl',
            field=models.TextField(blank=True, help_text='Optional message to employer', null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='name_tl',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='notes_en',
            field=models.TextField(blank=True, help_text='Special terms or notes', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='notes_tl',
            field=models.TextField(blank=True, help_text='Special terms or notes', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='termination_reason_en',
            field=models.TextField(blank=True, default='', help_text='Reason for termination request', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='termination_reason_tl',
            field=models.TextField(blank=True, default='', help_text='Reason for termination request', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='terms_en',
            field=models.TextField(blank=True, help_text='Contract terms and conditions', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='terms_tl',
            field=models.TextField(blank=True, help_text='Contract terms and conditions', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='description_tl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='tasks_en',
            field=models.TextField(default='job to be done', help_text='List specific tasks expected from the worker.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='tasks_tl',
            field=models.TextField(default='job to be done', help_text='List specific tasks expected from the worker.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='title_tl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljobapplication',
            name='message_en',
            field=models.TextField(blank=True, help_text='Optional message to employer', null=True),
        ),
        migrations.AlterField(
            model_name='historicaljobapplication',
            name='message_tl',
            field=models.TextField(blank=True, help_text='Optional message to employer', null=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='general_category',
            field=models.ForeignKey(blank=True, help_text='Broad category this job belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_categories', to='jobs.generalcategory'),
        ),
    ]
