# Generated by Django 5.1.6 on 2026-01-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_contract_end_time_contract_start_time_and_more'),
        ('jobs', '0019_generalcategory_contract_job_description_en_and_more'),
    ]

    operations = [
    ]
