# Generated by Django 5.1.6 on 2026-01-16 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_add_video_to_jobprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobapplication',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Current step in hiring process (1-8)'),
        ),
        migrations.AddField(
            model_name='historicaljobapplication',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted for Interview'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interview Completed'), ('offer_pending', 'Offer Pending'), ('contract_sent', 'Contract Sent'), ('contract_negotiation', 'Contract Negotiation'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', help_text='Current stage in the hiring workflow', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Current step in hiring process (1-8)'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted for Interview'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interview Completed'), ('offer_pending', 'Offer Pending'), ('contract_sent', 'Contract Sent'), ('contract_negotiation', 'Contract Negotiation'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', help_text='Current stage in the hiring workflow', max_length=30),
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When the interview is scheduled')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Interview duration in minutes')),
                ('interview_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In Person')], default='video', max_length=20)),
                ('video_room_id', models.CharField(blank=True, help_text='Jitsi room ID', max_length=100)),
                ('video_room_url', models.URLField(blank=True, help_text='Jitsi room URL')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('employer_notes', models.TextField(blank=True, help_text='Notes before interview')),
                ('interview_feedback', models.TextField(blank=True, help_text='Feedback after interview')),
                ('interview_rating', models.IntegerField(blank=True, help_text='1-5 rating of candidate', null=True)),
                ('meeting_notes', models.TextField(blank=True, help_text='Additional meeting instructions')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for phone interviews', max_length=20)),
                ('location_address', models.TextField(blank=True, help_text='Address for in-person interviews')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_employer', models.BooleanField(default=False)),
                ('reminder_sent_worker', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='jobs.jobapplication')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Schedule',
                'verbose_name_plural': 'Interview Schedules',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
