# Generated by Django 5.1.6 on 2025-11-22 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobapplication_options_contract_agreed_rate_and_more'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedWord',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        # Remove the old field first
        migrations.RemoveField(
            model_name='report',
            name='reporter_user',
        ),
        # Add new fields
        migrations.AddField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(blank=True, help_text='Job posting being reported (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='User who submitted the report', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot or evidence supporting the report', null=True, upload_to='reports/screenshots/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(help_text='Reason for the report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, help_text='User being reported (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'status'], name='reports_rep_reporte_3f63bc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_post', 'status'], name='reports_rep_reporte_097c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        # Now add unique_together AFTER all fields are added
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'reported_user', 'reported_post')},
        ),
    ]
