# Generated by Django 5.1.6 on 2025-02-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcategory_remove_jobposting_client_job'),
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
